### ISSUE TITLE
Excetion is thrown on Meteor 1.0.4 rc

### ISSUE THREAD

**Issue by ernestorocha** [meteorhacks/meteor-collection-utils#1]
I know it's too early to open this issue, but probably It will remain broken on 1.0.4 final.

When using `meteorhacks:aggregate` which depends on this package, `meteor run` throws this exception:

`````` ^
W20150309-22:13:07.489(-3)? (STDERR) TypeError: Cannot call method 'bind' of undefined
W20150309-22:13:07.489(-3)? (STDERR)     at [object Object].MongoInternals.RemoteCollectionDriver.open (packages/meteorhacks:collection-utils/index.js:5:1)
W20150309-22:13:07.489(-3)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:104:1)
W20150309-22:13:07.489(-3)? (STDERR)     at [object Object].ns.Collection (packages/matb33:collection-hooks/collection-hooks.js:190:1)
W20150309-22:13:07.489(-3)? (STDERR)     at ServiceConfiguration.configurations._ensureIndex.service (packages/service-configuration/service_configuration_common.js:8:1)
W20150309-22:13:07.489(-3)? (STDERR)     at /Users/ernestorocha/Documents/app/.meteor/local/build/programs/server/packages/service-configuration.js:54:4
W20150309-22:13:07.489(-3)? (STDERR)     at /Users/ernestorocha/Documents/app/.meteor/local/build/programs/server/packages/service-configuration.js:111:3
W20150309-22:13:07.489(-3)? (STDERR)     at /Users/ernestorocha/Documents/app/.meteor/local/build/programs/server/boot.js:222:10
W20150309-22:13:07.489(-3)? (STDERR)     at Array.forEach (native)
W20150309-22:13:07.490(-3)? (STDERR)     at Function._.each._.forEach (/Users/ernestorocha/.meteor/packages/meteor-tool/.1.0.42-rc.2.12aimnq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150309-22:13:07.490(-3)? (STDERR)     at /Users/ernestorocha/Documents/app/.meteor/local/build/programs/server/boot.js:117:5```
``````

**Comment by arunoda** [comment]
May be. I'll give it a shot.

**Comment by arunoda** [comment]
Okay, I've fixed this and published a new version of `meteorhacks:aggregate`.

Update like this:

``` shell
meteor refresh
meteor update meteorhacks:aggregate
```

> Make sure you've meteorhacks:aggregate@1.2.0

**Comment by rgould** [comment]
I can confirm that updating fixes this issue.

**Comment by arunoda** [comment]
Great.
